Repository ChoiGoLee/SNS-Terminal, pull requests merged in 2025-09, with the labels that each got.

#21 [feat]댓글,좋아요,공유 컴포넌트 버튼 추가 및 SVG 아이콘 플러그인 설치
  package-lock.json
  package.json
  public/vite.svg
  src/assets/icons/close-line.svg
  src/assets/icons/code-fill.svg
  src/assets/icons/heart-line.svg
  src/components/common/CommentButton.tsx
  src/components/common/LikeButton.tsx
  src/components/common/ShareButton.tsx
  src/pages/home/index.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: bug

#24 23 fix pr template edit
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitmessage.txt
Labels: bug

#25 fit(ui): 버튼 컴포넌트 아이콘 경로 정리 및 공유 기능 제거
  public/icons/heart-fill.svg
  src/assets/icons/comment.svg
  src/assets/icons/heart-line.svg
  src/components/common/CommentButton.tsx
  src/components/common/LikeButton.tsx
  src/components/common/ShareButton.tsx
Labels: bug

#32 #12 Feat 마크다운 렌더링 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/css/Markdown.module.css
  src/assets/icons/comment.svg
  src/components/common/Markdown.tsx
  src/index.css
  src/pages/home/index.tsx
  src/pages/post-create/index.jsx
Labels: enhancement

#38 26 refactor 프로젝트 구조 정리 및 파일 정규화
  src/pages/post-create/index.jsx
  src/pages/post-create/index.tsx
Labels: bug

#42 Feature/설명 컴포넌트
  .gitignore
  src/assets/icons/logout.svg
  src/assets/icons/post.svg
  src/assets/icons/search-g.svg
  src/assets/icons/trash.svg
  src/components/common/Description.tsx
  src/docs/JSDOCS.md
Labels: enhancement

#50 refactor: 선언되지 않은 type 선언 및 에러 해결
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/Markdown.tsx
  src/components/common/SideBar.tsx
  src/components/common/SidebarButton.tsx
  src/components/constants/sidebarItems.ts
  src/index.css
  src/pages/home/index.tsx
  src/pages/login/index.tsx
  src/pages/messages/index.tsx
  src/pages/post-create/index.tsx
  src/pages/post-detail/index.tsx
  src/pages/profile-setting/index.tsx
  src/pages/profile/index.tsx
  src/pages/search/index.tsx
  src/pages/settings/index.tsx
  tsconfig.app.json
  tsconfig.node.json
  tsconfig.path.json
  vite.config.ts
Labels: bug

#54 Feat/53 messagebubble component
  src/components/common/MessageBubble.tsx
  src/pages/home/index.tsx
  src/pages/messages/index.tsx
Labels: enhancement

#56 Feature/게시글,게시글 상세 컴포넌트
  src/components/common/Avatar.tsx
  src/components/common/CommentButton.tsx
  src/components/common/LikeButton.tsx
  src/components/common/PostCard.tsx
  src/components/common/UserLevel.tsx
  src/pages/home/index.tsx
  src/pages/post-detail/index.tsx
Labels: enhancement

#61 60 feat/api infrastructure setup
  src/services/apiWrapper.ts
  src/services/tokenManager.ts
  src/types/api.ts
  src/utils/configs.ts
Labels: enhancement

#81 59/feat api post create connect
  public/icons/close-red-lg.svg
  public/icons/daily-fill.svg
  public/icons/daily.svg
  public/icons/folder-fill.svg
  public/icons/folder.svg
  public/icons/question-fill.svg
  public/icons/question.svg
  public/icons/stack-fill.svg
  public/icons/stack.svg
  public/icons/study-fill.svg
  public/icons/study.svg
  public/icons/tag-fill.svg
  public/icons/tag.svg
  src/pages/post-create/components/PostTypeButton.tsx
  src/pages/post-create/index.tsx
Labels: enhancement

#83 글자수 인코딩시 최대 10byte
  src/components/common/PostCard.tsx
  src/utils/validation.ts
Labels: enhancement

#84 fix/한글 최대 5글자 그외10글자로 수정
  src/utils/validation.ts
Labels: enhancement

#85 59/feat api post create connect
  src/components/common/Header.tsx
  src/pages/post-create/index.tsx
Labels: enhancement

#93 Update README.md with project details, features, and setup instructions.
  README.md
Labels: documentation
